const express = require('express');
const router = express.Router();
const bodyParser = require('body-parser');
const User = require('./../Model/User');
const RegistController = require('./../Controller/AuthController');
router.use(bodyParser.urlencoded({extended: true}));
router.use(bodyParser.json());
router.post('/login',RegistController.authUser );
router.post('/regist',RegistController.registerUser);
module.exports = router;
